// Custom icon static resources

import {
  AccountBookOutline,
  AppstoreOutline,
  AreaChartOutline,
  ArrowLeftOutline,
  BulbOutline,
  DashboardOutline,
  DashOutline,
  DatabaseOutline,
  DeleteOutline,
  DownloadOutline,
  EditOutline,
  ExceptionOutline,
  FolderOpenOutline,
  FunnelPlotOutline,
  GroupOutline,
  InfoOutline,
  LineChartOutline,
  LinkOutline,
  PauseCircleOutline,
  PlayCircleOutline,
  PlusOutline,
  PoundOutline,
  ProfileOutline,
  SettingOutline,
  ThunderboltOutline,
  UnorderedListOutline,
  UsergroupDeleteOutline,
  WalletOutline
} from '@ant-design/icons-angular/icons';

export const ICONS = [
  InfoOutline,
  BulbOutline,
  ProfileOutline,
  ExceptionOutline,
  LinkOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  AppstoreOutline,
  DashOutline,
  AccountBookOutline,
  DatabaseOutline,
  AreaChartOutline,
  GroupOutline,
  DashboardOutline,
  SettingOutline,
  AppstoreOutline,
  LineChartOutline,
  DownloadOutline,
  PlayCircleOutline,
  PauseCircleOutline,
  WalletOutline,
  FolderOpenOutline,
  ThunderboltOutline,
  ArrowLeftOutline,
  FunnelPlotOutline,
  UnorderedListOutline,
  PoundOutline,
  UsergroupDeleteOutline,
];
